name: ReadmeUpdate
# Only trigger, when the build workflow succeeded
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
jobs:
  update_readme:
    if: ${{!startsWith(github.event.head_commit.message, '[RELEASE]') || !startsWith(github.event.head_commit.message, '[README]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm install --save-dev embedme
      - name: Update README
        run: |
          npx embedme README.md
      - name: Commit and push if it was changed
        run: |
          git config --global user.name 'Firebolt Casters'
          git config --global user.email 'nilsbaumgartner@live.de'
          git add -A
          git commit -m "[README] Updated README"
          git push
